.TH MYKERNEL 1 2025\-04\-13
.SH NAME

.B mykernel:
Change files and directories owner and permissions recursively.
.SH SYNOPSIS

mykernel usage: mykernel [\-h] [\-\-version] [\-\-config]
.SH DESCRIPCI\('ON

.PP
Esta aplicaci\('on tiene los siguientes par\('ametros obligatorios:
.PP
.RS
.B \-\-config
.RE
.PP
.RS
.RS
Escribe un fichero de configuraci\('on en /etc/mykernel/mykernel.ini
.RE
.RE
.SH AYUDA PARA LA CONFIGURACI\('ON DE MYKERNEL.INI

.PP
.B [cpupower]
.PP
.RS
.B cpu_hz
.RE
.PP
.RS
.RS
N\('umero de la frequencia de escalado de la CPU. El valor por defecto es su valor m\('aximo. D\('ejalo como est\('a si no sabes que est\('as haciendo.
.RE
.RE
.PP
.B [initramfs]
.PP
.RS
.B encrypted_root_partition
.RE
.PP
.RS
.RS
Nombre del dispostivo de la partici\('on cifrada. Vac\('io si no hay cifrado en tu sistema.
.RE
.RE
.PP
.B [grub]
.PP
.RS
.B efi
.RE
.PP
.RS
.RS
Verdadero si tienes un sistema EFE con una tabla de particiones gpt. False si el sistema usa una partici\('on dos con un bloque mbr.
.RE
.RE
.PP
.RS
.B boot_directory
.RE
.PP
.RS
.RS
Ruta al directorio boot. Por defecto /boot.
.RE
.RE
.PP
.RS
.B efi_target
.RE
.PP
.RS
.RS
Puede ser uno de los objetivos de grub para efi. x86_64\-efi, i386\-pc...
.RE
.RE
.PP
.RS
.B efi_partition
.RE
.PP
.RS
.RS
Nombre de la partici\('on donde est\('a el directorio EFI
.RE
.RE
.PP
.RS
.B mbr_device
.RE
.PP
.RS
.RS
Nombre del dispositivo donde el mbr va a ser instalado. Solo funciona para sistemas que no son EFI.
.RE
.RE
